import { Vehicle, VehicleType, BlogPost, Review } from '@/types';

// Real customer reviews, sourced verbatim (light punctuation cleanup only)
// from the business's public Google profile via Birdeye. Do NOT invent
// reviews here — and do NOT feed these into Review/AggregateRating JSON-LD:
// Google treats third-party-collected review markup as self-serving spam.
export const REVIEWS: Review[] = [
  { name: 'Kesia S.',    location: 'Google review', stars: 5, text: 'Our driver arrived promptly, was courteous and thoughtful, drove smoothly, and the car was clean.' },
  { name: 'MarDeb B.',   location: 'Google review', stars: 5, text: 'Our go-to service. Used many times recently. Always punctual.' },
  { name: 'Ali S.',      location: 'Google review', stars: 5, text: 'The best service ever! He took me and my family from Boston to New York. Awesome service and great deal!' },
  { name: 'Temesgen M.', location: 'Google review', stars: 5, text: 'The best service — very kind people.' },
];

export const FLEET: Vehicle[] = [
  {
    id: '2',
    name: 'Suburban',
    type: VehicleType.VIP,
    maxPassengers: 6,
    maxLuggage: 6,
    imageUrl: '/fleet/suburban.avif',
    features: ['Spacious Cabin', 'Extra Cargo Space', 'Child Seat Available'],
  },
  {
    id: '3',
    name: 'Escalade',
    type: VehicleType.VIP,
    maxPassengers: 6,
    maxLuggage: 6,
    imageUrl: '/fleet/cadillac-suv.avif',
    features: ['Privacy Partition', 'Premium Sound System', 'Ambient Lighting'],
  },
  {
    id: '4',
    name: 'GLE 450',
    type: VehicleType.VIP,
    maxPassengers: 4,
    maxLuggage: 4,
    imageUrl: '/fleet/mercedes-gle-450.avif',
    features: ['Premium Leather', 'Extra Cargo Space', 'Child Seat Ready'],
  },
  {
    id: '1',
    name: 'Sedan',
    type: VehicleType.VIP,
    maxPassengers: 3,
    maxLuggage: 3,
    imageUrl: '/fleet/c300.avif',
    features: ['Leather Seating', 'Professional Chauffeur'],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    slug: 'logan-airport-car-service',
    title: 'Car Service to Logan Airport — Why a Black Car Beats Rideshare',
    createdAt: '2025-05-10',
    coverImageUrl: '/blogs/logan-airport.avif',
    excerpt: 'Why a professional car service beats rideshare every time at Logan.',
    content: '<p>Boston Logan International (BOS) is one of the busiest airports on the East Coast. For travelers who need to be somewhere on time, a rideshare just does not cut it. Surge pricing, unreliable pickups, and unfamiliar drivers make airport rides stressful.</p><p>Old Colony Chauffeur provides a better option — a fixed-price, professional car service with terminal-side pickup. Your driver monitors your flight in real time, so if you land early or late, they are already there. No waiting in the TNC lot, no phone calls trying to find your driver. Just a clean car, a professional driver, and a smooth ride into Boston, Dedham, or wherever you are headed.</p>',
  },
  {
    id: 'b2',
    slug: 'dedham-ma-car-service',
    title: 'Dedham MA Car Service — Your Local Ride Solution',
    createdAt: '2025-05-01',
    coverImageUrl: '/blogs/boston-seaport.avif',
    excerpt: 'Professional car service based in Dedham serving all of Greater Boston.',
    content: '<p>If you live or work in Dedham, MA, you know how inconvenient it can be to get a reliable ride into Boston or out to Logan Airport. Ride apps are unpredictable, parking downtown is expensive, and commuter rail does not always fit your schedule.</p><p>Old Colony Chauffeur is your local answer. Based in the area, we know Dedham and every route into the city. Whether you need an early morning airport drop-off, a corporate ride to the Financial District, or an event car for a night out, we make it easy. Just call or submit a ride request online.</p>',
  },
  {
    id: 'b3',
    slug: 'gillette-stadium-ride',
    title: 'Game Day at Gillette — Skip the Route 1 Traffic',
    createdAt: '2025-04-20',
    coverImageUrl: '/blogs/gillette-stadium.avif',
    excerpt: 'Get to Foxboro without the parking nightmare.',
    content: '<p>Route 1 on game day is a test of patience. Whether you are heading to Foxboro for a Patriots game or a summer concert, the drive — and the parking — can take hours. There is a better way.</p><p>Book a ride with Old Colony Chauffeur. We drop you at the most convenient pedestrian entry and coordinate a precise pickup for after the event. Your driver handles the traffic. You enjoy the game.</p>',
  },
  {
    id: 'b4',
    slug: 'harvard-mit-graduation-ride',
    title: 'Harvard & MIT Graduation — Luxury Rides for Families',
    createdAt: '2025-04-10',
    coverImageUrl: '/blogs/harvard-mit.avif',
    excerpt: 'Comfortable group transportation for graduation week in Cambridge.',
    content: '<p>Graduation week in Cambridge means street closures, full parking garages, and a lot of proud families trying to get to the same place at the same time. Instead of stressing over logistics, let us handle the driving.</p><p>Old Colony Chauffeur provides group-friendly vehicles perfect for families visiting for Harvard and MIT commencement. We navigate the closures so you can focus on celebrating.</p>',
  },
  {
    id: 'b5',
    slug: 'boston-to-cape-cod-ride',
    title: 'Boston to Cape Cod — Luxury Ride Without the Traffic Stress',
    createdAt: '2025-04-01',
    coverImageUrl: '/blogs/boston-to-cape.avif',
    excerpt: 'Skip the Route 3 headache and ride in comfort to the Cape.',
    content: '<p>Summer on Cape Cod is worth it — but the drive on Route 3 and over the Sagamore Bridge can ruin the mood before you even arrive. Skip the stress and ride down in comfort.</p><p>We provide direct transfers to Hyannis, Woods Hole ferry terminals, and anywhere along the Cape. Climate-controlled, clean, and on time — so your vacation starts the moment you leave your door.</p>',
  },
  {
    id: 'b6',
    slug: 'td-garden-celtics-bruins',
    title: 'TD Garden Nights — Arrive Ready, Leave Easy',
    createdAt: '2025-03-20',
    coverImageUrl: '/blogs/td-garden.avif',
    excerpt: 'Professional rides to Celtics and Bruins games at TD Garden.',
    content: '<p>North Station on game night is packed. Finding parking near TD Garden costs a fortune, and walking back to your car late at night is not always the best plan. Book a ride instead.</p><p>Old Colony Chauffeur drops you right at the arena and picks you up after the game. No parking, no stress — just door-to-door service so you can enjoy the night.</p>',
  },
  {
    id: 'b7',
    slug: 'boston-winter-travel',
    title: 'Boston Winter Rides — Professional Drivers in Any Weather',
    createdAt: '2025-03-05',
    coverImageUrl: '/images/winter-travel.jpg',
    excerpt: "Stay safe on the road during Boston's toughest winters.",
    content: "<p>Boston winters are no joke. Nor'easters, black ice, and packed snow can make driving dangerous and slow. If you have an early flight or an important meeting, this is not the time to risk your own car on Storrow Drive.</p><p>Our vehicles are winter-ready and our drivers are experienced in Boston's cold-weather conditions. Book a safe, professional ride and leave the winter driving to us.</p>",
  },
  {
    id: 'b8',
    slug: 'newbury-street-shopping-ride',
    title: 'Newbury Street Shopping — Drop-Off, Pick-Up, Done',
    createdAt: '2025-02-20',
    coverImageUrl: '/blogs/back-bay.avif',
    excerpt: 'Skip the Back Bay parking and enjoy a stress-free shopping trip.',
    content: "<p>Newbury Street has Boston's best boutiques, but finding parking in Back Bay is a headache. Your driver drops you at the shops, you spend the day browsing, and we pick you up whenever you are ready — bags and all.</p><p>It is the simplest way to enjoy a shopping day in the city without the parking meter anxiety.</p>",
  },
  {
    id: 'b9',
    slug: 'boston-wedding-transportation',
    title: 'Boston Wedding Transportation — Cars for Your Big Day',
    createdAt: '2025-02-10',
    coverImageUrl: '/blogs/boston-wedding.avif',
    excerpt: 'Professional wedding day rides across Boston and Dedham.',
    content: '<p>Your wedding day should be about you, not logistics. Old Colony Chauffeur coordinates transportation for bridal parties and guests across Boston, Dedham, and surrounding venues — from historic Beacon Hill churches to North Shore estates.</p><p>We arrive early, keep to your timeline, and make sure everyone gets where they need to be in comfort and style.</p>',
  },
  {
    id: 'b10',
    slug: 'boston-to-nyc-private-car',
    title: 'Boston to New York City — Private Car, No Hassle',
    createdAt: '2025-01-28',
    coverImageUrl: '/blogs/boston-to-nyc.avif',
    excerpt: 'Door-to-door rides between Boston and Manhattan.',
    content: '<p>Skip the train delays and airport chaos. A private car from Boston to New York City gives you full flexibility — leave when you want, stop if you need to, and arrive at your exact destination.</p><p>Our drivers handle the I-95 corridor so you can work, rest, or just enjoy the ride. It is the smart way to travel beyond the Acela.</p>',
  },
  {
    id: 'b11',
    slug: 'berkshires-fall-foliage-trip',
    title: 'Berkshires Fall Foliage — A Scenic Day Ride',
    createdAt: '2025-01-15',
    coverImageUrl: '/blogs/berkshires-fall.avif',
    excerpt: "Explore Massachusetts's fall colors with a professional driver.",
    content: "<p>The Berkshires offer some of the best fall foliage in New England. Skip the driving and let us take you through the Mohawk Trail, the Clark Art Institute, and the charming streets of Stockbridge — all in the comfort of a clean, quiet vehicle.</p>",
  },
  {
    id: 'b12',
    slug: 'bcec-convention-transport',
    title: 'Boston Convention Center — Event Rides Made Simple',
    createdAt: '2025-01-05',
    coverImageUrl: '/blogs/boston-convention.avif',
    excerpt: 'Professional car service for BCEC conferences and large events.',
    content: '<p>The Boston Convention and Exhibition Center draws thousands of visitors for biotech, tech, and corporate summits. Getting in and out efficiently matters. Our drivers know the best approaches to the BCEC and can handle multi-stop pickups for executive teams.</p>',
  },
  {
    id: 'b13',
    slug: 'kendall-square-boston-rides',
    title: 'Kendall Square to Boston — Fast, Reliable Rides',
    createdAt: '2024-12-20',
    coverImageUrl: '/blogs/kendall-square.avif',
    excerpt: 'Car service connecting Cambridge and the Boston Financial District.',
    content: '<p>Executives and researchers moving between Kendall Square and Boston need a ride they can count on. No surge pricing, no guessing — just a professional driver ready when you are, getting you across the Charles River on time.</p>',
  },
  {
    id: 'b14',
    slug: 'fenway-park-red-sox-ride',
    title: 'Fenway Park — Get to the Game Without the Parking Headache',
    createdAt: '2024-12-10',
    coverImageUrl: '/blogs/fenway-park.avif',
    excerpt: 'Easy drop-off and pickup for Red Sox games at Fenway.',
    content: "<p>Fenway Park is surrounded by some of the city's tightest streets and most expensive parking. Book a ride instead — we drop you right by the Jersey Street gates and pick you up when the game ends, no matter what time.</p>",
  },
  {
    id: 'b15',
    slug: 'boston-marathon-rides',
    title: 'Boston Marathon Week — Getting Around City Closures',
    createdAt: '2024-12-01',
    coverImageUrl: '/blogs/boston-marathon.avif',
    excerpt: 'Reliable rides during Boston Marathon road closures.',
    content: "<p>Marathon Monday closes major routes through Back Bay and the Fenway. If you need to get somewhere in the city that day, our drivers know the permitted routes and can get you where you are going without the guesswork.</p>",
  },
  {
    id: 'b16',
    slug: 'newport-ri-day-trip',
    title: 'Newport, RI Day Trip — Comfortable Ride from Boston',
    createdAt: '2024-11-20',
    coverImageUrl: '/blogs/newport-ri.avif',
    excerpt: 'Relax on the way to Newport with a professional driver.',
    content: "<p>Newport is just 90 minutes from Boston but feels like a world away. Skip driving yourself and let us take you to the Breakers, Cliff Walk, and Bowen's Wharf. We handle the route while you enjoy the scenery.</p>",
  },
  {
    id: 'b17',
    slug: 'boston-gala-event-rides',
    title: 'Boston Gala & Charity Events — Arrive in Style',
    createdAt: '2024-11-10',
    coverImageUrl: '/blogs/boston-museum.avif',
    excerpt: "Professional car service for Boston's top charity events and galas.",
    content: "<p>When the event calls for black tie, your ride should match. We provide clean, professionally detailed vehicles for MFA events, museum galas, and charity dinners across the city. Arrive looking sharp, leave without worrying about parking.</p>",
  },
  {
    id: 'b18',
    slug: 'longwood-medical-rides',
    title: 'Longwood Medical Area — Reliable Rides for Patients & Professionals',
    createdAt: '2024-11-01',
    coverImageUrl: '/blogs/longwood-medical.avif',
    excerpt: "Dependable car service to Boston's top hospitals and medical centers.",
    content: '<p>Getting to the Longwood Medical Area for an early appointment or a long shift is stressful enough. Our drivers provide quiet, comfortable rides so you can prepare or decompress on the way. Reliable, on time, every time.</p>',
  },
  {
    id: 'b19',
    slug: 'manchester-airport-transfer',
    title: 'Manchester Airport Car Service — Skip the Logan Traffic',
    createdAt: '2024-10-20',
    coverImageUrl: '/blogs/boston-to-manchester.avif',
    excerpt: 'Professional airport rides to Manchester-Boston Regional Airport.',
    content: '<p>MHT is often overlooked, but it can save you significant time and hassle compared to Logan. We provide smooth, direct transfers from Boston and Dedham to Manchester-Boston Regional Airport — so you get the best of both worlds.</p>',
  },
  {
    id: 'b20',
    slug: 'boston-theater-district-rides',
    title: 'Boston Theater District — Rides to the Wang, Opera House & More',
    createdAt: '2024-10-10',
    coverImageUrl: '/blogs/boston-theater.avif',
    excerpt: 'Easy drop-off and pickup for Boston theater and concert nights.',
    content: '<p>A night at the Wang Theatre or the Citizens House of Blues deserves a ride that matches. We drop you at the door and pick you up after the show — no parking stress, no walking in the rain.</p>',
  },
  {
    id: 'b21',
    slug: 'corporate-roadshow-boston',
    title: 'Corporate Roadshow Boston — Professional Rides Between Meetings',
    createdAt: '2024-09-25',
    coverImageUrl: '/blogs/corporate-roadshow.avif',
    excerpt: 'Multi-stop corporate car service across Boston for investor meetings.',
    content: '<p>Coordinating investor meetings across Boston, Cambridge, and the Seaport requires precision. Our corporate car service handles multi-stop itineraries so your team can focus on the presentation, not the commute.</p>',
  },
  {
    id: 'b22',
    slug: 'north-end-dining-rides',
    title: 'North End Dining — No Parking, No Problem',
    createdAt: '2024-09-15',
    coverImageUrl: '/blogs/north-end-dining.avif',
    excerpt: 'Enjoy dinner in the North End without the parking nightmare.',
    content: "<p>The North End has Boston's best Italian food and absolutely no parking. We drop you at Hanover Street and pick you up when you are done — simple as that. Great dinner, easy night.</p>",
  },
  {
    id: 'b23',
    slug: 'boston-to-providence-rides',
    title: 'Boston to Providence — Comfortable Rides to the RI Capital',
    createdAt: '2024-09-05',
    coverImageUrl: '/blogs/boston-to-providence.avif',
    excerpt: 'Professional car service between Boston and Providence, RI.',
    content: '<p>Whether you are heading to Providence for business, a visit, or a night out in Federal Hill, we make the trip easy. A quiet, comfortable ride between two great cities — no train, no parking garage.</p>',
  },
  {
    id: 'b24',
    slug: 'private-jet-fbo-boston',
    title: 'Private Aviation Transfers — Hanscom FBO & Logan Private Terminal',
    createdAt: '2024-08-20',
    coverImageUrl: '/blogs/private-jet-fbo.avif',
    excerpt: 'Ramp-side car service for private jet arrivals around Boston.',
    content: '<p>For clients flying private through Hanscom Field or the Logan FBOs, we coordinate ramp-side pickup with discretion and speed. Your driver is positioned and ready the moment you step off the aircraft.</p>',
  },
  {
    id: 'b25',
    slug: 'beacon-hill-rides',
    title: 'Beacon Hill — Historic Neighborhood, Professional Rides',
    createdAt: '2024-08-10',
    coverImageUrl: '/blogs/beacon-hill.avif',
    excerpt: 'Smooth rides through the narrow streets of Beacon Hill.',
    content: "<p>Beacon Hill's cobblestone streets are beautiful — and notoriously hard to navigate. Our drivers know every corner of the neighborhood, making your arrival smooth and your departure easy, no matter where you are headed next.</p>",
  },
  {
    id: 'b26',
    slug: 'boston-cruise-port-rides',
    title: 'Boston Cruise Port — Start Your Vacation Right',
    createdAt: '2024-07-25',
    coverImageUrl: '/blogs/boston-maritime.avif',
    excerpt: 'Comfortable car service to the Flynn Cruiseport in Boston.',
    content: '<p>Heading out on a cruise from Black Falcon Terminal? We drop you and your luggage right at the pier so you can check in without the stress of parking or a last-minute rideshare scramble. Start your vacation the right way.</p>',
  },
  {
    id: 'b27',
    slug: 'boston-holiday-lights-tour',
    title: 'Boston Holiday Lights — A Festive Night Out',
    createdAt: '2024-07-10',
    coverImageUrl: '/blogs/boston-holiday.avif',
    excerpt: 'Enjoy Boston holiday events and lights with a professional driver.',
    content: '<p>From the trees along Commonwealth Avenue to the lights at Quincy Market, Boston in December is beautiful. Book a car for your holiday party, dinner, or evening out and enjoy the city without fighting for parking in the cold.</p>',
  },
  {
    id: 'b28',
    slug: 'boston-family-rides',
    title: 'Boston Family Rides — School Events, Sports & Errands',
    createdAt: '2024-06-20',
    coverImageUrl: '/blogs/harvard-mit.avif',
    excerpt: 'Reliable family car service for everyday needs around Boston.',
    content: '<p>Not every ride is for business or a big event. Sometimes you just need a dependable driver to get the kids to a game, handle a busy day of errands, or pick up relatives from Logan. Old Colony Chauffeur is here for those days too.</p><p>Our Mercedes GLE 450 fits families comfortably, and every driver is professional and punctual. Book for a one-time need or set up regular pickups.</p>',
  },
  {
    id: 'b29',
    slug: 'boston-daily-commuter-rides',
    title: 'Daily Commuter Car Service — Flat-Rate Rides into Boston',
    createdAt: '2024-06-05',
    coverImageUrl: '/blogs/corporate-roadshow.avif',
    excerpt: 'Why Boston commuters are switching from taxis and rideshares to black car service.',
    content: '<p>If you commute regularly between Dedham, Canton, or the suburbs into downtown Boston, the cost of taxis and the unreliability of rideshare apps adds up fast. A scheduled black car service gives you a fixed price, a driver who shows up on time, and no surge pricing — ever.</p><p>Old Colony Chauffeur works with regular commuters to set up recurring ride schedules. Same driver, same time, same quality — every day.</p>',
  },
];
